spring:
  redis:
    host: ${REDIS_HOST}
    port: 12165
    password: ${REDIS_PASS}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journalApp
      auto-index-creation: true

  main:
    allow-circular-references: true

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /journal




weather:
  api:
    key: ${WEATHER_API_KEY}


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${E_USERMNAME}
    password: ${E_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true