weather:
  api:
    key: ${WEATHER.API_KEY}

spring:
  redis:
    host: ${REDIS_HOST}
    port: 10609
    password: ${REDIS_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journalApp
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_EMAIL}
    password: ${JAVA_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-circular-references: true

server:
  port: 8080
  servlet:
    context-path: /journal






























#logging:
#  level:
#    net:
#      vansh:
#        journalApp: ERROR

#logging:
#  level:
#    net:
#      vansh:
#        journalApp:
#          service:
#            UserService: OFF

#logging:
#  level:
#    root: OFF

